### ISSUE TITLE
License unknown

### ISSUE THREAD

**Issue by ypid** [anthill/C_OpeningHours#1]
Hi

Could you consider putting this library under a license so that it is clear what it can be used for. [I personally like the LGPL-3.0](https://github.com/opening-hours/opening_hours.js/issues/133) but that is your decision :wink:

**Comment by Asphahyre** [comment]
I need to read licences descriptions first, to match the one I want to apply.
If I don't use a CreativeCommons licence, I might take another with less restrictions. :smile:

Anyway, this will be done by the end of the week.

**Comment by ypid** [comment]
Thanks :+1:

Note that CC licenses are not ideal for Software: https://wiki.creativecommons.org/index.php/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F
